language: node_js
node_js: stable
# 指定需要sudo权限
sudo: required

# Travis-CI Caching
cache:
  directories:
    - node_modules
    - public

# 只在更新 develop 时执行
branches:
  only:
    - develop

before install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "DCMMC"
  - git config user.email "xwt97294597@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/github_token/${Github_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle
